#docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: canteen_db
      MYSQL_USER: canteen_user
      MYSQL_PASSWORD: techBteam
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: ["sh", "-c", "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend-web
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend-web:/app
    ports:
      - "5173:5173"

volumes:
  mysql_data:
